import { Project } from 'ts-morph';

const project = new Project();
project.addSourceFilesAtPaths('src/**/*.ts');

const sourceFile = project.getSourceFile('src/persistence/database.ts');
if (!sourceFile) throw new Error('database.ts not found');

const classDecl = sourceFile.getClass('AppDatabase');
if (!classDecl) throw new Error('AppDatabase class not found');

const methodsToRemove = [
  'getWelcomeGroupSetting',
  'listWelcomeGroupSettings',
  'saveWelcomeGroupSetting',
  'getWelcomeRuntime',
  'updateWelcomeRuntime',
  'hasWelcomeBaselineParticipant',
  'addWelcomeBaselineParticipant',
  'isWelcomeGroupBaselineInitialized',
  'markWelcomeGroupBaselineInitialized',
  'claimWelcomeParticipant',
  'getPollConfiguration',
  'savePollConfiguration',
  'listPollTemplates',
  'listHiddenPollTemplates',
  'hidePollTemplateForAssistant',
  'restorePollTemplateForAssistant',
  'restoreAllDefaultPollsForAssistant',
  'getPollTemplate',
  'savePollTemplate',
  'deletePollTemplate',
  'restoreDefaultPollTemplates',
  'getPollDateOverride',
  'listPollDateOverrides',
  'savePollDateOverride',
  'deletePollDateOverride',
  'claimPollDelivery',
  'getPollDelivery',
  'getPollTemplateIdForLocalDate',
  'beginPollAttempt',
  'completePollAttempt',
  'listPollSendHistory',
  'listPollUsage',
  'listCommands',
  'getCommand',
  'getDefaultCommandResponse',
  'restoreCommandDefault',
  'getCommandById',
  'saveCommand',
  'deleteCommand',
  'listKeywords',
  'replaceKeywords',
  'setSilence',
  'getSilenceRemainingMs',
  'getGroupModerationProfile',
  'listGroupModerationProfiles',
  'saveGroupModerationDraft',
  'markGroupModerationAnalyzing',
  'failGroupModerationAnalysis',
  'saveCompiledGroupModeration',
  'recordGroupModerationTest',
  'listGroupModerationTests',
  'updateGroupModerationTestStatus',
  'setGroupModerationEnabled',
  'replaceGroupModerationRecipients',
  'listGroupModerationRecipients',
  'getModerationSettings',
  'saveModerationSettings',
  'listModerationGroupSettings',
  'saveModerationGroupSettings',
  'listModerationRules',
  'getModerationRule',
  'createModerationRule',
  'updateModerationRule',
  'deleteModerationRule',
  'listModerationTerms',
  'createModerationTerm',
  'deleteModerationTerm',
  'createModerationCase',
  'listModerationCases',
  'reviewModerationCase',
  'getModerationEvidence',
  'getModerationRecurrence',
  'saveModerationRecurrence',
  'resetModerationRecurrence',
  'decrementModerationRecurrence',
  'incrementModerationMetric',
  'getModerationMetrics',
  'expireModerationEvidence',
  'anonymizeExpiredModerationCases',
  'getAutomaticMessageConfiguration',
  'saveAutomaticMessageConfiguration',
  'getAutomaticTemplateCustomization',
  'restoreAutomaticTemplate',
  'claimScheduledDelivery',
  'createManualDelivery',
  'createWelcomeDelivery',
  'updateScheduledDelivery',
  'listScheduledDeliveries',
  'getAutomaticGroupBackoffRemainingMs',
  'setAutomaticGroupBackoff',
  'listLinkedGroups',
  'setGroupBlocked',
  'isGroupBlocked',
  'synchronizeBotGroup',
  'markMissingBotGroups',
  'markBotGroupNotMember',
  'canBotSendToGroup',
  'listActiveBotGroupIds',
  'setBotGroupBlocked',
  'listBotGroups',
  'resolveBotGroupKey',
  'upsertDetectedGroup',
  'synchronizeDetectedGroup',
  'listGroups',
  'getGroupById',
  'listGroupsByStatus',
  'markMissingGroups',
  'markGroupBotNotMember',
  'archiveGroup',
  'restoreGroup',
  'deleteGroupRecord',
  'deleteBotGroupRecord',
  'removeInactiveBotGroupsMissingFromScan',
  'setGroupPublicListing',
  'listPublicOperationalGroups',
  'canAuthorizeGroup',
  'canSendToGroup',
  'setGroupAuthorized',
  'isGroupAuthorized',
  'previewGroupCleanup',
  'cleanupInactiveGroups'
];

for (const methodName of methodsToRemove) {
  const method = classDecl.getMethod(methodName);
  if (method) {
    method.remove();
  }
}

sourceFile.fixUnusedIdentifiers();
project.saveSync();
console.log('Removed community methods from database.ts');
